### ISSUE TITLE
Problem with TypeError: ...FloatingDType 

### ISSUE THREAD

**Issue by JD2112** [maurijlozano/ISCompare#2]
@maurijlozano 
## What is the 
`   ********************************************
   *****   ISCompare
   *****   Version: 1.0.1
   *****   Developed by Mauricio J. Lozano
   *****   github.com/maurijlozano
   ********************************************
   Please cite: 

   Easy identification of insertion sequence mobilization events
   in related bacterial strains with ISCompare. 
   E.G. Mogro, N. Ambrosis, M.J. Lozano
   doi: https://doi.org/10.1101/2020.10.16.342287
   Instituto de Biotecnología y Biología Molecular
   CONICET - CCT La Plata - UNLP - FCE

   Downloaded from: https://github.com/maurijlozano/ISCompare

Directory  consensusMap  already exists.
Query: ['MT-1_consensus_seqret.genbank'] Ref: ['MT-2_consensus_seqret.genbank']
Copying files to consensusMap folder, and extracting fasta files from genbank.
query.fasta generated.
ref.fasta generated.
6 ISs found on the query genome...
Step1: Removing identical scaffolds: Query --> Reference ...
0 identical scaffolds removed from the analysis...
Step2: Testing for new IS on the query...
6 ISs found on the reference genome...
Step3: Removing identical scaffolds: Reference --> Query ...
0 identical scaffolds removed from the analysis...
Step4: Testing for IS missing on the query...
Step5: Consolidating results and annotating data...
Traceback (most recent call last):
  File "/mnt/SD2/Jyotirmoys/Backup_20211108/BIN21P012_MT/ISCompare/./ISCompare.py", line 2297, in <module>
    FinalResults[['ISstart', 'ISend', 'Start1', 'End1', 'REF.Start1','REF.End1','Start2', 'End2', 'REF.Start2','REF.End2']] = FinalResults[['ISstart', 'ISend', 'Start1', 'End1', 'REF.Start1','REF.End1','Start2', 'End2', 'REF.Start2','REF.End2']].astype("Float32")
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/generic.py", line 5808, in astype
    results = [
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/generic.py", line 5809, in <listcomp>
    self.iloc[:, i].astype(dtype, copy=copy)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/internals/blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/dtypes/cast.py", line 1105, in astype_nansafe
    return dtype.construct_array_type()._from_sequence(arr, dtype=dtype, copy=copy)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/arrays/floating.py", line 261, in _from_sequence
    values, mask = coerce_to_array(scalars, dtype=dtype, copy=copy)
  File "/opt/sw/bioinfo-tools/sources/anaconda3/envs/multiqc/lib/python3.9/site-packages/pandas/core/arrays/floating.py", line 143, in coerce_to_array
    raise TypeError(f"{values.dtype} cannot be converted to a FloatingDtype")
TypeError: object cannot be converted to a FloatingDtype
`

## How to solve
I solved this by changing the line# 2297 of ISCompare.py from .astype("Float32") to .astype("float32")

**Comment by maurijlozano** [comment]
Thank you for your comment. I'm already correcting the code.
Kind regards
