### ISSUE TITLE
ISComapre failed to run

### ISSUE THREAD

**Issue by safinaARK** [maurijlozano/ISCompare#3]
Dear ISCompare Team,

I m encountering the following error:

```
Directory  ISCompare_out  created.
Query: ['/mnt/e/Working/Shigella/Data/shigella_flexneri/out_africa_flex_53/annotation/ERR126957/ERR126957.gbk'] Ref: ['/mnt/e/Working/Shigella/Data/shigella_flexneri/flex.gbk']
Copying files to ISCompare_out folder, and extracting fasta files from genbank.
query.fasta generated.
ref.fasta generated.
Retrieving IS sequences from ISFinder database.
Please cite: Siguier P. et al. (2006)
ISfinder: the reference centre for bacterial insertion sequences.
Nucleic Acids Res. 34: D32-D36
ISFinder database URL: http://www-is.biotoul.fr.
SSL: CERTIFICATE_VERIFY_FAILED. Do you want to continue without SSL certificate verification?
Please input Y/N: y

175 IS sequences downloaded from ISFinder database.
819 ISs found on the query genome...
Step1: Removing identical scaffolds: Query --> Reference ...
452 identical scaffolds removed from the analysis...
Step2: Testing for new IS on the query...
/home/sar/miniconda3/lib/python3.6/site-packages/pandas/core/frame.py:7138: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort,
Traceback (most recent call last):
  File "ISCompare.py", line 2177, in <module>
    missingIS = testIS(rseq, qseq,MiddleMissingISID,consecutiveIS)
  File "ISCompare.py", line 853, in testIS
    extractSeqFromREFGB(refFileGB,keep,refISSurroundsFromQuery,surroundingLen,shift)
  File "ISCompare.py", line 525, in extractSeqFromREFGB
    coordStart = coordStart - shift
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

The command i ran is :

 python ISCompare.py -q /mnt/e/Working/Shigella/Data/shigella_flexneri/out_africa_flex_53/annotation/ERR126957/ERR126957.gbk -r /mnt/e/Working/Shigella/Data/shigella_flexneri/flex.gbk -o ISCompare_out -c -I -p

Can you please help me to resolve the error

Thanks

SAR

**Comment by maurijlozano** [comment]
Dear SAR
I'm trying to replicate your error in order to solve it. However, in my PC the program run without error. The error Python is reporting is that the program is trying to subtract a number to a text variable. In the reported error shift is the number 0 while coordStart is apparently a text when it should be also a number.

I am currently testing with: Python 3.8.10, numpy 1.21.4, pandas 1.3.5

Maybe if you send me all the files in the output folder I can try to discover where it fails...
