### ISSUE TITLE
TypeError: can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by mboum** [maurijlozano/ISCompare#7]
Hi,

I have used ISCompare.py successfully before. 
A few months later, I am trying to check the results on an updated file and am facing an error:

Traceback (most recent call last):
  File "/Users/mathilde/Documents/GitHub/ISCompare/ISCompare.py", line 20, in <module>
    from dna_features_viewer import BiopythonTranslator
  File "/Users/mathilde/opt/anaconda3/lib/python3.9/site-packages/dna_features_viewer/__init__.py", line 3, in <module>
    from .GraphicRecord import GraphicRecord
  File "/Users/mathilde/opt/anaconda3/lib/python3.9/site-packages/dna_features_viewer/GraphicRecord/__init__.py", line 1, in <module>
    from .GraphicRecord import GraphicRecord
  File "/Users/mathilde/opt/anaconda3/lib/python3.9/site-packages/dna_features_viewer/GraphicRecord/GraphicRecord.py", line 2, in <module>
    from ..biotools import find_narrowest_text_wrap
  File "/Users/mathilde/opt/anaconda3/lib/python3.9/site-packages/dna_features_viewer/biotools.py", line 38, in <module>
    _aa1: _aa3[0] + _aa3[1:].lower() for (_aa1, _aa3) in zip(aa1 + "*", aa3 + ["*"])
TypeError: can only concatenate tuple (not "str") to tuple

This error does not have anything to do with the new input file, nor with any input file (I tried to run it on the old ones as well).
It actually appears even when just trying :
`python ISCompare.py -h`

I tried downloading it from scratch and also reinstalling the python library dna_features_viewer but this did not solve it. Any idea of where the problem is?
Thank you very much,
Best regards,
Mathilde

**Comment by maurijlozano** [comment]
Hi, I recently used it with no problem, at least on linux. I am using dna-features-viewer vs 3.1.2, and python 3.10.6. Maybe you could try to install or update dna-features-viewer with pip? Are you running inside a conda environment?
Mauricio
